route:
  group_by: ['alertname', 'cluster', 'service']
  receiver: 'slack-dev'

receivers:
- name: 'slack-dev'
  slack_configs:
  - channel: '#prometheus-dev-alerts'
    api_url: 'https://hooks.slack.com/services/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'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"

- name: 'default-receiver'
  slack_configs:
  - channel: '#alerts'
    api_url: 'https://hooks.slack.com/services/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'
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"