groups:
- name: example
  rules:
  - alert: InstanceDownLabels
    expr: up
    for: 5s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 seconds."
  - alert: InstanceDownNoLabels
    expr: up
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: "Instance down"
      description: "Something has been down for more than 5 seconds."